CREATE TABLE SHIPWRECK(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(2000),
	CONDITION VARCHAR(255),
	DEPTH INT,
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	YEAR_DISCOVERED INT
);

CREATE TABLE DIRECTLIST(
	ID INT AUTO_INCREMENT,
	DESCRIPTION VARCHAR(2000),
	CODE INT,
	STATUS BOOLEAN
);
CREATE TABLE INDIRECTLIST(
	ID INT AUTO_INCREMENT,
	DESCRIPTION VARCHAR(2000),
	CODE INT,
	STATUS BOOLEAN
);
