CREATE TABLE LISTDATA(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(2000),
	DESCRIPTION VARCHAR(2000),
	ACTIVE BOOLEAN
);
CREATE TABLE LISTDATAITEMS(
	ID INT AUTO_INCREMENT,
	CODE INT,
	NAME VARCHAR(2000),
	DESCRIPTION VARCHAR(2000),
	ACTIVE VARCHAR(2000),
	PARENT_LIST_ID INT
);
CREATE TABLE FOUNDATIONDATACOLUMN(
	ID INT AUTO_INCREMENT,
	UI_COLUMN_NAME VARCHAR(2000),
	HOVER_HELP VARCHAR(2000),
	UNIQUE_COLUMN VARCHAR(2000),
	INPUT_TYPE VARCHAR(2000),
	VALUE VARCHAR(2000),
	MANDATORY BOOLEAN,
	SORT_ORDER INT,
	EDITABLE BOOLEAN,
	LENGTH INT
);