CREATE TABLE LISTDATA(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(2000),
	DESCRIPTION VARCHAR(2000),
	ACTIVE BOOLEAN
);
CREATE TABLE LISTDATAITEMS(
	ID INT AUTO_INCREMENT,
	CODE INT,
	NAME VARCHAR(2000),
	DESCRIPTION VARCHAR(2000),
	ACTIVE VARCHAR(2000),
	PARENT_LIST_ID INT
);